### ISSUE TITLE
WebSocket 성능 테스트

### ISSUE THREAD

**Issue by jjm159** [jungle-royale/jungle-royale-game-server#6]
- [ ] 성능 테스트 도구를 통한 웹소켓 서버 부하 테스트

```yaml
config:
  target: "ws://localhost:8000/room?roomId=test"  # WebSocket 서버 주소
  phases:
    - duration: 1                 # 테스트 지속 시간 (초)
      arrivalRate: 2000              # 초당 1명의 사용자 연결
  processor: "./tester.js"        # JavaScript로 메시지 생성 위임
scenarios:
  - engine: "ws"
    flow:
      - function: "randomMessage" 
      - think: 0.01  # * 1000
```
```javascript
const protobuf = require("protobufjs");
const faker = require("faker"); // 랜덤 값 생성용 (선택적으로 사용)
let root = null;

// Protobuf 정의 파일 로드
protobuf.load("message.proto", (err, loadedRoot) => {
  if (err) throw err;
  root = loadedRoot;
});

module.exports = {
  randomMessage: (context, events, done) => {
    if (!root) {
      console.error("Protobuf not loaded yet");
      return done();
    }

    // 메시지 타입 정의
    const Wrapper = root.lookupType("Wrapper");
    const ChangeDir = root.lookupType("ChangeDir");
    const DoDash = root.lookupType("DoDash");
    const CreateBullet = root.lookupType("CreateBullet");

    // 랜덤 메시지 생성
    const messageType = Math.floor(Math.random() * 3);
    let message;
    switch (messageType) {
      case 0: // ChangeDir
        message = Wrapper.create({
          MessageType: {
            changeDir: ChangeDir.create({
              angle: Math.random() * 360,
              isMoved: Math.random() > 0.5,
            }),
          },
        });
        break;
      case 1: // DoDash
        message = Wrapper.create({
          MessageType: {
            doDash: DoDash.create({
              dash: Math.random() > 0.5,
            }),
          },
        });
        break;
      case 2: // CreateBullet
        message = Wrapper.create({
          MessageType: {
            createBullet: CreateBullet.create({
              playerId: faker.datatype.uuid(), // 랜덤 Player ID
              startX: Math.random() * 1000,   // 랜덤 X 좌표
              startY: Math.random() * 1000,   // 랜덤 Y 좌표
              angle: Math.random() * 360,     // 랜덤 각도
            }),
          },
        });
        break;
    }

    // Protobuf 메시지 직렬화
    const buffer = Wrapper.encode(message).finish();

    // WebSocket으로 전송
    context.ws.send(buffer);

    // console.log("Sent Protobuf message:", message);
    done();
  },
};

```

100 ~ 2000명의 client가 동시접속하여 0.01초 간격으로 1000번의 메시지를 보내는 게임서버 부하 테스트 진행

braodcast와 send가 동시에 하나의 socket에 쓰기를 하여 오류 발생 및 수정 완료

테스트 결과 2000명의 플레이어까지 동작 완료
